### PR TITLE
Added collaborator recommendation

### PR DESCRIPTION
**Pull request by buseg**
Owner of the project can now get a recommendation for collaborators. An example API call would be like the following:

api/users/get_collaborator_recommendation/?project_id=1

This endpoint will return at most 10 users. If the number of users in the database who are not a member of the specified project is smaller than 10, it can return less than 10 users. All users are sorted according to the following formula:

(1 + number of requirements matching with user expertise) * ( 1 + (user rating/10)) * (if project owner follows the user 1.2 else 1)

### CODE REVIEW

**Comment by mhrfky** [comment]
I am not sure but maybe, we can increase the parameter of the follow feature. I am underlining the "I am not sure" part

**Comment by mhrfky** [comment]
And I am not sure if you have handled it already, but does it check for the already invited collaborators or if the user is already a member of the project?

**Comment by buseg** [comment]
> And I am not sure if you have handled it already, but does it check for the already invited collaborators or if the user is already a member of the project?

It checks for the members but not the invited users, good point. I'll implement that.

**Comment by buseg** [comment]
Added check for invited users, increased the number of recommendations to 10, and changed follower coefficient to 1.2.

**Comment by buseg** [comment]
The limit on the number of recommendations is lifted with the suggestion of @mhrfky . All the users in the system except the members of the project and already invited users will be returned sorted by their relevance.

**Pull request merged**
