### PR TITLE
Create issue_template.md

### PR DESCRIPTION
**Pull request by buseg**
I added a file for the issue template please check if there are any additions necessary. #129

### CODE REVIEW

**Comment by Chuchichachtli** [comment]
I think we should add the project to this sentence : **I'm submitting a ... (remove the irrelevant one) "in the Front-End Project"** etc.

**Review by mhrfky — COMMENTED** [review]
I think there should be keywords for the issues related to subgroups. Such as frontend, backend, android

**Comment by ybedirhanpak** [comment]
I think it is sufficient as a general purpose issue template. We could create different templates for each type, eg. bug report, feature request, documentation for a better organization. IMO we should merge this and discuss it in a meeting

**Comment by buseg** [comment]
> I think there should be keywords for the issues related to subgroups. Such as frontend, backend, android

I thought this could be done by adding labels to the issue, this is already in use.

**Pull request merged**
